### ISSUE TITLE
html mime during fetching the image

### ISSUE THREAD

**Issue by dgrechka** [LostPetInitiative/poiskzoo-ru-crawler#13]
05:29:25 160643:	 Card dir already exists. Consider it as processed. skipping it
05:29:25 159963:	 Card dir already exists. Consider it as processed. skipping it
05:29:25 160626:	 Card dir already exists. Consider it as processed. skipping it
05:29:25 159835:	 Card dir already exists. Consider it as processed. skipping it
05:29:25 165457:	Fetching card...
05:29:25 165446:	 Card dir already exists. Consider it as processed. skipping it
05:29:25 165451:	Fetching card...
05:29:25 165441:	 Card dir already exists. Consider it as processed. skipping it
05:29:25 165249:	 Card dir already exists. Consider it as processed. skipping it
05:29:25 165450:	 Card dir already exists. Consider it as processed. skipping it
05:29:26 165459:	Downloaded card
05:29:26 165459:	Trying to geocode "Россия, г. Вильнюс, "...
05:29:26 165457:	Downloaded card
05:29:26 165451:	Downloaded card
05:29:26 165459:	Trying to geocode "Россия, Вильнюс, "...
05:29:27 165457:	Downloaded image for card (576113 bytes; mime text/html; charset=windows-1251)
05:29:27 165457:	Trying to geocode "Россия, г. Пенза, октябрьский"...
05:29:27 165459:	Trying to geocode "Россия, г. Вильнюс"...
05:29:28 165451:	Downloaded image for card (576113 bytes; mime text/html; charset=windows-1251)
05:29:28 165451:	Trying to geocode "Россия, г. Самара, Село Гаврилова Поляна"...
05:29:28 165459:	Trying to geocode "Россия, Вильнюс"...
05:29:29 165457:	Successfully geocoded "Россия, г. Пенза, октябрьский" as lat:52.449313 lon:44.118795
05:29:29 Unsupported image mime type: text/html; charset=windows-1251
05:29:29 165457:	Panic during fetching of card Unsupported image mime type: text/html; charset=windows-1251
panic: Unsupported image mime type: text/html; charset=windows-1251 [recovered]
	panic: Unsupported image mime type: text/html; charset=windows-1251
goroutine 29 [running]:
github.com/LostPetInitiative/poiskzoo-ru-crawler/pkg/crawler.DoCardJob.func1()
	/app/pkg/crawler/downloader.go:27 +0xac
panic({0x6b7660, 0xc000668060})
	/usr/local/go/src/runtime/panic.go:884 +0x212
log.Panicf({0x71fe61?, 0x1f?}, {0xc000697b10?, 0xc000668040?, 0x0?})
	/usr/local/go/src/log/log.go:395 +0x67
github.com/LostPetInitiative/poiskzoo-ru-crawler/pkg/crawler.EncodeImage({0xc0007b0000, 0x8ca71, 0xac000}, {0xc000022d80, 0x1f})
	/app/pkg/crawler/cardJson.go:119 +0xe5
github.com/LostPetInitiative/poiskzoo-ru-crawler/pkg/crawler.NewCardJSON(0xc00021fb20, 0xc0002c02b0, {0x71fbf6, 0x1e}, {0xc0007b0000, 0x8ca71, 0xac000}, {0xc000022d80, 0x1f})
	/app/pkg/crawler/cardJson.go:85 +0x278
github.com/LostPetInitiative/poiskzoo-ru-crawler/pkg/crawler.DoCardJob(0x28651, {0xc00002000a, 0x3}, 0xc00017e090)
	/app/pkg/crawler/downloader.go:83 +0xc1d
main.main.func1()
	/app/main.go:192 +0x6c
created by main.main
	/app/main.go:198 +0xefb

**Comment by dgrechka** [comment]
Attempt to fetch the image redirects to the poiskzoo landing page
